name: capstone-msprime
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=25.4.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - demes=0.2.3
  - gsl=2.7
  - icu=75.1
  - joblib=1.5.2
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.5
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - msprime=1.3.4
  - ncurses=6.5
  - numpy=2.3.4
  - openssl=3.5.4
  - pandas=2.3.3
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - readline=8.2
  - referencing=0.37.0
  - rpds-py=0.28.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tskit=0.6.4
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - build==1.3.0
      - click==8.3.0
      - packaging==25.0
      - pip==24.3.1
      - pip-tools==7.4.1
      - pyproject-hooks==1.2.0
